[package]
name = "hodei_provider"
version = "0.1.0"
edition = "2024"

[dependencies]
hodei_provider_derive = { path = "../hodei_provider_derive" }
cedar-policy = "4.7.0"
inventory = "0.3.15"
kernel = { path = "../kernel" }
